### ISSUE TITLE
dependencies error

### ISSUE THREAD

**Issue by hmkim** [esnapd/DegeneratePrimerTools#10]
Hi, esnapd

```
library(devtools)
install_github('esnapd/DegeneratePrimerTools')
```

> ERROR: dependencies ‘msa’, ‘ggtree’ are not available for package ‘DegeneratePrimerTools’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/DegeneratePrimerTools’
> Error: Command failed (1)

Do you check this? I install the dependencies in manually.

**Comment by zachcp** [comment]
Hi @hmkim,

msa and ggtree are packages in the bioconductor ecosystem.  To obtain them you will need to install them using Bioconductor:

```
source("https://bioconductor.org/biocLite.R")
biocLite(c("msa", "ggtree"))
```

I will make a note of it on the README.md

thanks,
zach cp
