### ISSUE TITLE
Retrieval functions issue

### ISSUE THREAD

**Issue by lemetrec** [esnapd/DegeneratePrimerTools#4]
in retrieval-functions.R
pfamdfs doesn't return a data frame, so pfamdfs$PFAM_ID returns NULL. On lines 239-240

```
pfamdfs    <- map(pfamids, ~retrieve_PFAM_ids(., alignmenttype=alignmenttype))
  
  if (length(unique(pfamdfs$PFAM_ID)) == 1) {
```

**Comment by zachcp** [comment]
we chatted offline. I believe this was a library reloading issue. reopen if still needed
